### ISSUE TITLE
Toggling backlight

### ISSUE THREAD

**Issue by KIRUYXAN** [Taleuxss/SelectiveMining#2]
Please add a function so that you can turn off the backlight of the blocks

**Comment by Taleuxss** [comment]
https://github.com/Taleuxss/NoOutline/releases/tag/release is this what you mean bro?

**Comment by Taleuxss** [comment]
i also made a version where the block outline is removed for blocks other than the one selected, is that what you want?

**Comment by KIRUYXAN** [comment]
Damn, after I wrote this issue, it stopped outlighting blocks by itself

**Comment by Taleuxss** [comment]
thats wonderful, im glad my mod wasnt the issue
