### ISSUE TITLE
Optional Block State Match

### ISSUE THREAD

**Issue by m-sarabi** [Taleuxss/SelectiveMining#3]
Can you please add a config option so that selective mining takes block state into account? like waterlogged, age, etc.

it is specially useful when harvesting crops in order to only break fully grown ones, but can have other uses too. (like breaking incorrectly placed rotational blocks)

**Comment by Taleuxss** [comment]
Understood.

**Comment by Taleuxss** [comment]
Great, I hope you're happy.
